INSERT INTO EMPLOYEE ("ID","NAME","BIRTHDAY","SALARY","FUNCTION") VALUES ('1','Fulano',CURRENT_TIMESTAMP,'1000.00','DEVELOPER');
INSERT INTO EMPLOYEE ("ID","NAME","BIRTHDAY","SALARY","FUNCTION") VALUES ('2','Beltrano',CURRENT_TIMESTAMP,'5000.00','PO');
INSERT INTO EMPLOYEE ("ID","NAME","BIRTHDAY","SALARY","FUNCTION") VALUES ('3','Ciclano',CURRENT_TIMESTAMP,'10000.00','MANAGER');